/**
 * Proactive Engagement Phone Selector — PCF Entry Point
 * Version: 1.0.3
 *
 * Bridges the PCF lifecycle (init / updateView / getOutputs / destroy) to the
 * React component tree.  The class is intentionally thin — all UI logic lives
 * in EngageDialSelectorApp.tsx.
 *
 * Key responsibilities:
 *   • Detect customerid changes via context.updatedProperties and increment a
 *     reload counter so the React component re-fetches customer data.
 *   • Resolve the 8 configurable phone field properties from the manifest into
 *     PhoneFieldDef arrays passed to the React component.
 *   • Store the latest JSON payload generated by the React component.
 *   • Return that payload through getOutputs() so the PCF framework can write
 *     it to the alex_proactive_engagement field.
 */

import { IInputs, IOutputs } from "./generated/ManifestTypes";
import { EngageDialSelectorApp } from "./components/EngageDialSelectorApp";
import { PhoneFieldDef } from "./types";
import * as React from "react";

// ---------------------------------------------------------------------------
// Label-to-field maps — display label (the text content of <value> in the
// manifest, which is what EnumProperty.raw returns at runtime) → logical
// Dataverse field name used in the Web API $select query.
// ---------------------------------------------------------------------------

const CONTACT_LABEL_TO_FIELD: Readonly<Record<string, string>> = {
  "Mobile Phone": "mobilephone",
  "Telephone 1":  "telephone1",
  "Telephone 2":  "telephone2",
  "Telephone 3":  "telephone3",
};

const ACCOUNT_LABEL_TO_FIELD: Readonly<Record<string, string>> = {
  "Main Phone":    "telephone1",
  "Other Phone":   "telephone2",
  "Telephone 3":   "telephone3",
  "Address Phone": "address1_telephone1",
};

// ---------------------------------------------------------------------------
// Default display labels — used when a slot has no value configured yet
// (PCF returns "" for unconfigured Enum properties, not null/undefined).
// These labels match the first dropdown option shown in the form designer.
// "None" means the slot is intentionally empty and should be skipped.
// ---------------------------------------------------------------------------

const DEFAULT_CONTACT_LABELS = ["Mobile Phone", "Telephone 1", "Telephone 2", "Telephone 3"];
const DEFAULT_ACCOUNT_LABELS = ["Main Phone", "Other Phone", "Telephone 3", "Address Phone"];

// ---------------------------------------------------------------------------
// Helper — resolve a single manifest enum slot to a PhoneFieldDef or null
// ---------------------------------------------------------------------------

function resolveSlot(
  raw: string | null | undefined,
  defaultLabel: string,
  labelToField: Readonly<Record<string, string>>
): PhoneFieldDef | null {
  // PCF returns "" (empty string) for unconfigured Enum properties; treat as
  // missing. Use an explicit ternary (not || or ??) to avoid the ESLint
  // prefer-nullish-coalescing rule while still catching empty strings.
  const displayLabel = (raw != null && raw !== "") ? raw : defaultLabel;
  // "None" means the customizer intentionally disabled this slot.
  if (!displayLabel || displayLabel === "None") return null;
  const field = labelToField[displayLabel];
  if (!field) return null;
  return { field, label: displayLabel };
}

// ---------------------------------------------------------------------------
// Helper — build a deduplicated PhoneFieldDef array from 4 slot values
// ---------------------------------------------------------------------------

function resolveFields(
  slots: (string | null | undefined)[],
  defaults: string[],
  labelToField: Readonly<Record<string, string>>
): PhoneFieldDef[] {
  const seenFields = new Set<string>();
  const result: PhoneFieldDef[] = [];
  for (let i = 0; i < slots.length; i++) {
    const def = resolveSlot(slots[i], defaults[i] ?? "None", labelToField);
    if (def && !seenFields.has(def.field)) {
      seenFields.add(def.field);
      result.push(def);
    }
  }
  return result;
}

// ---------------------------------------------------------------------------
// PCF Control class
// ---------------------------------------------------------------------------

export class EngageDialSelector
  implements ComponentFramework.ReactControl<IInputs, IOutputs>
{
  private _notifyOutputChanged!: () => void;
  private _currentPayload: string | undefined;

  /**
   * Incremented each time the customerid field changes on the form.
   * Passed as a prop so the React component's useEffect can react to it.
   */
  private _customerReloadVersion = 0;

  constructor() {
    // Intentionally empty — instance fields initialised above.
  }

  public init(
    context: ComponentFramework.Context<IInputs>,
    notifyOutputChanged: () => void,
    _state: ComponentFramework.Dictionary
  ): void {
    this._notifyOutputChanged = notifyOutputChanged;
  }

  public updateView(
    context: ComponentFramework.Context<IInputs>
  ): React.ReactElement {
    // Increment version whenever the customer lookup changes so the React
    // component knows to reload phone numbers.
    if (context.updatedProperties?.includes("customerId")) {
      this._customerReloadVersion++;
    }

    // Read the 8 configurable phone field slots from the manifest properties.
    const p = context.parameters;
    const contactFields = resolveFields(
      [
        (p as unknown as Record<string, {raw: string | null}>).contactField1?.raw,
        (p as unknown as Record<string, {raw: string | null}>).contactField2?.raw,
        (p as unknown as Record<string, {raw: string | null}>).contactField3?.raw,
        (p as unknown as Record<string, {raw: string | null}>).contactField4?.raw,
      ],
      DEFAULT_CONTACT_LABELS,
      CONTACT_LABEL_TO_FIELD
    );

    const accountFields = resolveFields(
      [
        (p as unknown as Record<string, {raw: string | null}>).accountField1?.raw,
        (p as unknown as Record<string, {raw: string | null}>).accountField2?.raw,
        (p as unknown as Record<string, {raw: string | null}>).accountField3?.raw,
        (p as unknown as Record<string, {raw: string | null}>).accountField4?.raw,
      ],
      DEFAULT_ACCOUNT_LABELS,
      ACCOUNT_LABEL_TO_FIELD
    );

    return React.createElement(EngageDialSelectorApp, {
      context,
      onPayloadReady: this._handlePayloadReady,
      customerReloadVersion: this._customerReloadVersion,
      contactFields,
      accountFields,
    });
  }

  public getOutputs(): IOutputs {
    return { engagementField: this._currentPayload };
  }

  public destroy(): void {
    // No subscriptions or timers to clean up.
  }

  // ---------------------------------------------------------------------------
  // Private handlers
  // ---------------------------------------------------------------------------

  /**
   * Called by EngageDialSelectorApp when the agent confirms a phone selection.
   * Stores the JSON payload and notifies the PCF framework so it can write the
   * value to alex_proactive_engagement on the form.
   */
  private _handlePayloadReady = (payload: string | null): void => {
    this._currentPayload = payload ?? undefined;
    this._notifyOutputChanged?.();
  };
}
